### ISSUE TITLE
not working on IE

### ISSUE THREAD

**Issue by notvitor** [WebApiContrib/WebApiContrib.Formatting.Xlsx#36]
First, Nice work done here.

I'm using it successfully with chrome and ff, but with IE it returns the file with wrong filename, not the file name setted in the class with [ExcelDocument("File name")], also the file type/extension is not recognized when prompted to save the file.

The filename returned comes with something as the name like,
=_utf-8_B_W1BvcnRhbCBDSVJKXS1bNS8xMS8yMDE0XS1bRXhwb3J0XS1bTGlzdGEgZGUgQcOnw7Vlc10ueGxzeA==_=

Thanks in advance.

By the way, my controller method content:

```csharp
var header = new MediaTypeWithQualityHeaderValue("application/vnd.ms-excel");
Request.Headers.Accept.Clear();
Request.Headers.Accept.Add(header);

var result = GetListOfObjects();//something similiar returning List<Object>
return Ok(result);
```

**Comment by jordangray** [comment]
Hey @notvitor! Sorry I took so long to get back. I know this is old now, but I wanted to at least give you something.

I think the reason the file name won't be coming back is because you're clearing the HTTP request headers. Here's how I'm setting the file name for the returned Excel document:

``` csharp
headers.ContentDisposition = new ContentDispositionHeaderValue("inline")
                                             { FileName = fileName };
```

…where `headers` is the `HttpContentHeaders` value passed in to the formatter's `SetDefaultContentHeaders` method. My suggestion is to either let the package set the headers for you, or to [take a look at that method](https://github.com/WebApiContrib/WebApiContrib.Formatting.Xlsx/blob/master/src/WebApiContrib.Formatting.Xlsx/XlsxMediaTypeFormatter.cs#L87) and at the default headers used to make sure nothing's missing. :)

If you're still having problems—or I've missed something obvious, which is absolutely possible—please get back to me! Could you also grab a copy of the headers that are being sent with the file, and what version of Office (or equivalent) you have installed?

**Comment by jordangray** [comment]
Haven't heard back on this for a while, so I'm going to close it for now. Feel free to reopen it if you have any more input, though!
